
title: La Passerelle
email: association@passerelle52.fr
description: >- # this means to ignore newlines until "baseurl:"
  Les actions de la Passerelle visent à lutter activement au quotidien contre l’isolement social 
  pour des publics majeurs, et à recréer des liens avec les acteurs sociaux, médicosociaux et 
  institutionnels ainsi que la société civile.
lang: fr
locale: fr_FR

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://passerelle52.fr"
logo: /img/logo-la-passerelle.png

facebook_username: LaPasserelle52
instagram_username: ?????????

facebook:
  publisher: LaPasserelle52

plugins:
  - jekyll-seo-tag

input: GFM
kramdown:
    parse_block_html: true
    parse_span_html: true

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
